# Generated by Django 4.2.15 on 2024-09-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("sno", models.AutoField(primary_key=True, serialize=False)),
                ("Employee_name", models.CharField(default="", max_length=255)),
                (
                    "Employee_id",
                    models.CharField(default="", max_length=255, unique=True),
                ),
                ("Employee_Department", models.CharField(default="", max_length=255)),
            ],
        ),
    ]
