# Generated by Django 4.2.15 on 2024-09-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Signup",
            fields=[
                ("sno", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(default="", max_length=255)),
                ("Email_id", models.CharField(max_length=255, unique=True)),
                ("Password", models.CharField(max_length=255)),
                ("Gender", models.CharField(max_length=50)),
                ("State", models.CharField(max_length=255)),
                ("Mobile", models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
