# Generated by Django 4.2.15 on 2024-09-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_common", "0004_contact_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.CharField(db_column="name", max_length=255),
        ),
        migrations.RenameField(
            model_name="contact",
            old_name="name",
            new_name="person_name",
        ),
    ]
