# Generated by Django 4.2.15 on 2024-09-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_common", "0006_alter_contact_person_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                ("sno", models.AutoField(primary_key=True, serialize=False)),
                ("Teacher_Name", models.CharField(max_length=255)),
                ("Department", models.CharField(max_length=255)),
                ("salary", models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="contact",
            name="person_name",
            field=models.CharField(db_column="name", max_length=255),
        ),
    ]
