# Generated by Django 4.2.15 on 2024-09-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_common", "0007_teacher_alter_contact_person_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="salary",
            field=models.IntegerField(db_column="salary"),
        ),
        migrations.RenameField(
            model_name="teacher",
            old_name="salary",
            new_name="Salary",
        ),
    ]
