# Generated by Django 4.2.15 on 2024-09-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_common", "0008_alter_teacher_salary_rename_salary_teacher_salary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="Salary",
            field=models.IntegerField(),
        ),
    ]
