# Generated by Django 4.2.15 on 2024-09-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_common", "0002_signup"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("sno", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("Email", models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
