# Generated by Django 4.2.15 on 2024-09-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_common", "0003_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="address",
            field=models.CharField(default="NaN", max_length=255),
        ),
    ]
