# Generated by Django 4.2.15 on 2024-09-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_common", "0005_alter_contact_name_rename_name_contact_person_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="person_name",
            field=models.CharField(max_length=255),
        ),
    ]
